language: scala
scala:
- 2.11.4
jdk:
- openjdk7
before_script: sh travis/before_script.sh
script:
- sbt ++$TRAVIS_SCALA_VERSION clean compile test:compile
- sbt ++$TRAVIS_SCALA_VERSION test
after_success:
- |
  test "${TRAVIS_PULL_REQUEST}" = 'false' && test "${TRAVIS_JDK_VERSION}" = 'openjdk7' && sbt 'set resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"' ++${TRAVIS_SCALA_VERSION} '+ publish'
branches:
  only:
  - master
env:
  global:
  - secure: XTMpQhzwum2Ntw5qJRxVClHs/xntjwjKNmVHzHS/ZAHqSBny99uSWnBihuu5oHwyPAHzlBmmkAHMzVoedeYx3Rnqq0aXW42GA/eEvMIa2lZE0aTD5WW136Ui5rpNxHKgtpkmbUCU6dh/htiZKPQXlBBsgX4lLdqDAxg5LOHY0gM=
  - secure: i3s97N4r0mTkgqJR/JY1lsSSSEjrQkfb60q+cuBZJcDdkHC+OHSE9r+JZ37pKsMGmHwQ/PeC5u9oplzSb6ISNDmMbfaozq7J0NOF9Ku5S6SFlkgQBt6DBPa+eR+WsQ2pxIUdfaXDdlOiCm7Ab4FYQU0U3I0GJJXki44jgK58piw=
notifications:
  email:
  - dcaoyuan@wandoujia.com
  - chenxingrun@wandoujia.com
